### PR TITLE
Multiple enhancements and fixes, including one incompatible metric value change

### PR DESCRIPTION
**Pull request by ferringb**
Pardon the size of this PR; I've been cleaning things for a while, and this turned into a much larger PR than I intended.  Unfortunately due to how I was just piling fixes/changes on as I went, breaking this up is a mild pain in the butt.  It can be done if desired, but I'd ask that any release is held off until all code here gets merged in- I cleaned up a fair bit.

This fixes:
* issue #9 (which required a newer version of lib/pq)
* issue #7; this also exposes the pool mode and user as an added bonus while fixing cardinality.
* issue #4 ; this adds `show config`, it also adds `show lists`, and `show databases`.  This is the source of most of the refactoring of collector- there needed to be two ways of parsing, K/V and row based.
* issue #10 is an upstream bug in pgbouncer, but this fixes a bug in the exporter that was hiding the actual cause.

This doesn't fix issue #5 , but it does fix misnamed metrics that are named 'seconds' but are actually 'ms'; the code doesn't change the metric name, it instead ensures the value exported matches the unit type for the metric.  This is the sole incompatibility that I've introduced, and it is contained in 5183bb5171d1b4ee037fd26ce9193c5c8ec0dfd9 , affecting the following metrics:
* stats_avg_query
* stats_avg_query_time
* stats_avg_wait_time
* stats_avg_xact_time
* stats_total_query_time
* stats_total_wait_time
* stats_total_xact_time

Finally, since the implementation got a non-trivial refactoring, I also dropped the dead code I encountered and tried to refactor the logic to be a bit more contained.  My expectation is that fixing issue #5 properly is probably best done via splitting the various definitions out of the code, and instead bundling them in as yaml files with bindata libs; that would allow maintaining both 'old' metric names and 'new' in parallel, and selecting which to export via a simpler internal pathway.

### CODE REVIEW

**Comment by bdronneau** [comment]
Hi @ferringb ,

I'm looking to put in place this exporter. Since this PR contains a lot evolutions/fixes, do you have any plan to finish to fix #5 ?

Best

**Comment by leominov** [comment]
I think it's never be merged :D

**Comment by leominov** [comment]
@bdronneau did you look at gocardless/pgbouncer_exporter?

**Comment by ferringb** [comment]
@bdronneau #5 should be actioned, but this is first step.  I'd suggest tracing what @leominov mentioned- the 'fork' I've got isn't something I'd like to maintain longer term.

**Comment by leominov** [comment]
gocardless/pgbouncer_exporter doesn't contains some metrics from this exporter :(

**Comment by leominov** [comment]
We will check another fork – kubedb/pgbouncer_exporter

**Comment by bdronneau** [comment]
Thank for the informations

**Comment by leominov** [comment]
Looks like kubedb/pgbouncer_exporter@initialchanges is what we need.

**Comment by tamalsaha** [comment]
@leominov , we are looking to maintain the fork https://github.com/kubedb/pgbouncer_exporter/pull/1 in KubeDB project.

**Pull request closed without merging**
